name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull in license data
      run: git clone https://github.com/nexB/scancode-toolkit.git
    - name: test dir entries
      run: ls
    - name: Move license data to correct location
      run: mv -v scancode-toolkit/src/licensedcode/data/licenses/* ./licenses/RAW/
    - name: Run tests
      run: cargo test --verbose
